# Generated by Django 3.0.8 on 2020-07-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20200726_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='modo_prepato',
            new_name='modo_preparo',
        ),
    ]
